### PR TITLE
Actual Line edit comments

### PR DESCRIPTION
**Pull request by TanyaS08**

### CODE REVIEW

**Comment by TanyaS08** [comment]
I didn't 're-wrap' the lines so it might be easier to pick up differences. Also I somehow managed to break the build 🙈

**Comment by FrancisBanville** [comment]
Thanks @TanyaS08, I'll integrate your changes next week!

**Comment by FrancisBanville** [comment]
Not sure what happened with the build. Perhaps something went wrong with the abstract?

**Comment by FrancisBanville** [comment]
Changes incorporated!

**Pull request closed without merging**
